# Generated by Django 5.0.4 on 2024-07-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caterapp', '0002_about_aboutfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('numbers', models.IntegerField()),
                ('count_name', models.CharField(max_length=50)),
            ],
        ),
    ]
