# Generated by Django 5.0.4 on 2024-07-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caterapp', '0007_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chefabout/')),
                ('chef_name', models.CharField(max_length=50)),
                ('chef_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='image',
            field=models.ImageField(upload_to='book/'),
        ),
    ]
