# Generated by Django 5.0.4 on 2024-07-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caterapp', '0009_servicecustomers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/')),
                ('date', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('test', models.CharField(max_length=50)),
            ],
        ),
    ]
