# Generated by Django 5.0.4 on 2024-07-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caterapp', '0010_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254)),
                ('phone1', models.CharField(max_length=50)),
                ('phone2', models.CharField(max_length=50)),
            ],
        ),
    ]
