# Generated by Django 5.0.4 on 2024-07-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caterapp', '0012_footer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
